### ISSUE TITLE
Clickhouse settings

### ISSUE THREAD

**Issue by igor-sitnikov** [TimonKK/clickhouse#68]
Hello
Can you answer for a question please? How can I set settings for clickhouse that are describing [here](https://clickhouse.tech/docs/ru/operations/settings/settings/)?

**Comment by TimonKK** [comment]
Hi,
You can pass them in config section:
```javascript
const clickhouse = new ClickHouse({
...
    config: {
      join_use_nulls: 1
   }
});
```

Or in query:
```javascript
clickhouse.query('SELECT * FROM table SSETTINGS join_use_nulls=1');

**Comment by RamonN334** [comment]
Ok, thank you very much. And I have one question yet. Lib supports all available setting? Because I attempt set two properties by first approach: date_time_input_format and date_time_output_format. First property sets without problem, but second throws an error: "404: Code: 115, e.displayText() = DB::Exception: Unknown setting date_time_output_format (version 20.8.12.2 (official build))".

**Comment by TimonKK** [comment]
The lib sends any setting which you pass to config. Maybe your version of database does not support this option. Would you try to use `date_time_output_format` in native clickhouse-client?
